/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as VisiteursRouteImport } from './routes/visiteurs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteursRoute = VisiteursRouteImport.update({
  id: '/visiteurs',
  path: '/visiteurs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/tarifs': typeof TarifsRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/tarifs': typeof TarifsRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/tarifs': typeof TarifsRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methode' | '/tarifs' | '/visiteurs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methode' | '/tarifs' | '/visiteurs'
  id: '__root__' | '/' | '/methode' | '/tarifs' | '/visiteurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodeRoute: typeof MethodeRoute
  TarifsRoute: typeof TarifsRoute
  VisiteursRoute: typeof VisiteursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visiteurs': {
      id: '/visiteurs'
      path: '/visiteurs'
      fullPath: '/visiteurs'
      preLoaderRoute: typeof VisiteursRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodeRoute: MethodeRoute,
  TarifsRoute: TarifsRoute,
  VisiteursRoute: VisiteursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
