/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as PourquoiRouteImport } from './routes/pourquoi'
import { Route as SimulerRouteImport } from './routes/simuler'
import { Route as VisiteursRouteImport } from './routes/visiteurs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiRoute = PourquoiRouteImport.update({
  id: '/pourquoi',
  path: '/pourquoi',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulerRoute = SimulerRouteImport.update({
  id: '/simuler',
  path: '/simuler',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteursRoute = VisiteursRouteImport.update({
  id: '/visiteurs',
  path: '/visiteurs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/pourquoi': typeof PourquoiRoute
  '/simuler': typeof SimulerRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/pourquoi': typeof PourquoiRoute
  '/simuler': typeof SimulerRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/pourquoi': typeof PourquoiRoute
  '/simuler': typeof SimulerRoute
  '/visiteurs': typeof VisiteursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methode' | '/pourquoi' | '/simuler' | '/visiteurs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methode' | '/pourquoi' | '/simuler' | '/visiteurs'
  id: '__root__' | '/' | '/methode' | '/pourquoi' | '/simuler' | '/visiteurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodeRoute: typeof MethodeRoute
  PourquoiRoute: typeof PourquoiRoute
  SimulerRoute: typeof SimulerRoute
  VisiteursRoute: typeof VisiteursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi': {
      id: '/pourquoi'
      path: '/pourquoi'
      fullPath: '/pourquoi'
      preLoaderRoute: typeof PourquoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simuler': {
      id: '/simuler'
      path: '/simuler'
      fullPath: '/simuler'
      preLoaderRoute: typeof SimulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visiteurs': {
      id: '/visiteurs'
      path: '/visiteurs'
      fullPath: '/visiteurs'
      preLoaderRoute: typeof VisiteursRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodeRoute: MethodeRoute,
  PourquoiRoute: PourquoiRoute,
  SimulerRoute: SimulerRoute,
  VisiteursRoute: VisiteursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
